// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGDApi.Data;

#nullable disable

namespace SGDApi.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20231001220511_SGD-31")]
    partial class SGD31
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SGDApi.Models.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AreaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<DateTime?>("FechaOrigen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaRevision")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioCreador")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int");

                    b.HasKey("AreaId");

                    b.HasIndex("UsuarioCreador");

                    b.HasIndex("UsuarioModificacion");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("SGDApi.Models.Comentario", b =>
                {
                    b.Property<int>("ComentarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ComentarioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComentarioId"));

                    b.Property<string>("Contenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaOrigen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaRevision")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioCreador")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int");

                    b.HasKey("ComentarioId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UsuarioCreador");

                    b.HasIndex("UsuarioModificacion");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("SGDApi.Models.Documento", b =>
                {
                    b.Property<int>("DocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DocumentoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentoId"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioCreador")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int");

                    b.HasKey("DocumentoId");

                    b.HasIndex("UsuarioCreador");

                    b.HasIndex("UsuarioModificacion");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("SGDApi.Models.Estados", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EstadoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("EstadoCodigo")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("EstadoNombre")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioCreador")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int");

                    b.Property<int?>("UsuariosCreadorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuariosModificacionUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("EstadoId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UsuariosCreadorUsuarioId");

                    b.HasIndex("UsuariosModificacionUsuarioId");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("SGDApi.Models.LogActividades", b =>
                {
                    b.Property<int>("LogActividadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogActividadId"));

                    b.Property<string>("LogActividadAccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LogActividadFecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuariosUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("LogActividadId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuariosUsuarioId");

                    b.ToTable("LogActividades");
                });

            modelBuilder.Entity("SGDApi.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TaskId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaOrigen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaRevision")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioCreador")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("int");

                    b.HasKey("TaskId");

                    b.HasIndex("AreaId");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("UsuarioCreador");

                    b.HasIndex("UsuarioModificacion");

                    b.HasIndex("UsuariosId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("SGDApi.Models.Usuarios", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<DateTime?>("FechaOrigen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaRevision")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioApellido")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("UsuarioCedula")
                        .HasMaxLength(13)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("UsuarioContrasena")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<string>("UsuarioCorreo")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("UsuarioLlaveQR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("UsuarioNombre")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("UsuarioTelefono")
                        .HasMaxLength(12)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("UsuarioTwoFactor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SGDApi.Models.Area", b =>
                {
                    b.HasOne("SGDApi.Models.Usuarios", "UsuariosCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreador");

                    b.HasOne("SGDApi.Models.Usuarios", "UsuariosModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacion");

                    b.Navigation("UsuariosCreador");

                    b.Navigation("UsuariosModificacion");
                });

            modelBuilder.Entity("SGDApi.Models.Comentario", b =>
                {
                    b.HasOne("SGDApi.Models.Task", "Task")
                        .WithMany("Comentarios")
                        .HasForeignKey("TaskId");

                    b.HasOne("SGDApi.Models.Usuarios", "UsuariosCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreador");

                    b.HasOne("SGDApi.Models.Usuarios", "UsuariosModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacion");

                    b.Navigation("Task");

                    b.Navigation("UsuariosCreador");

                    b.Navigation("UsuariosModificacion");
                });

            modelBuilder.Entity("SGDApi.Models.Documento", b =>
                {
                    b.HasOne("SGDApi.Models.Usuarios", "UsuariosCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreador");

                    b.HasOne("SGDApi.Models.Usuarios", "UsuariosModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacion");

                    b.Navigation("UsuariosCreador");

                    b.Navigation("UsuariosModificacion");
                });

            modelBuilder.Entity("SGDApi.Models.Estados", b =>
                {
                    b.HasOne("SGDApi.Models.Task", "Task")
                        .WithMany("Estados")
                        .HasForeignKey("TaskId");

                    b.HasOne("SGDApi.Models.Usuarios", "UsuariosCreador")
                        .WithMany()
                        .HasForeignKey("UsuariosCreadorUsuarioId");

                    b.HasOne("SGDApi.Models.Usuarios", "UsuariosModificacion")
                        .WithMany()
                        .HasForeignKey("UsuariosModificacionUsuarioId");

                    b.Navigation("Task");

                    b.Navigation("UsuariosCreador");

                    b.Navigation("UsuariosModificacion");
                });

            modelBuilder.Entity("SGDApi.Models.LogActividades", b =>
                {
                    b.HasOne("SGDApi.Models.Task", "Task")
                        .WithMany("LogActividades")
                        .HasForeignKey("TaskId");

                    b.HasOne("SGDApi.Models.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LogActividades_Usuarios_UsuarioId");

                    b.HasOne("SGDApi.Models.Usuarios", null)
                        .WithMany("LogActividades")
                        .HasForeignKey("UsuariosUsuarioId");

                    b.Navigation("Task");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SGDApi.Models.Task", b =>
                {
                    b.HasOne("SGDApi.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGDApi.Models.Documento", "Documento")
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGDApi.Models.Usuarios", "UsuariosCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreador");

                    b.HasOne("SGDApi.Models.Usuarios", "UsuariosModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacion");

                    b.HasOne("SGDApi.Models.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Documento");

                    b.Navigation("Usuarios");

                    b.Navigation("UsuariosCreador");

                    b.Navigation("UsuariosModificacion");
                });

            modelBuilder.Entity("SGDApi.Models.Task", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Estados");

                    b.Navigation("LogActividades");
                });

            modelBuilder.Entity("SGDApi.Models.Usuarios", b =>
                {
                    b.Navigation("LogActividades");
                });
#pragma warning restore 612, 618
        }
    }
}
